version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
  commands:
    - conda create -n vspec-vsm python=3.9
    - conda init bash
    - conda activate vspec-vsm
    - python3 -m pip install --user pipx
    - python3 -m pipx ensurepath
    - pipx install poetry
    - poetry install --with dev,docs,plot
    - cd docs
    - make html
    - cp --recursive build/html $READTHEDOCS_OUTPUT/html/