version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pipx install poetry==1.7.1
      # Tell poetry to not use a virtual environment
      # - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - poetry install --with docs,dev,plot

conda:
  environment: environment-rtd.yml

sphinx:
  configuration: docs/source/conf.py

