version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
  jobs:
    pre_create_environment:
       - conda update --yes --quiet --name=base --channel=defaults conda
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # Tell poetry to not use a virtual environment
      # - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - poetry install --with docs,dev,plot
      - conda envs list

conda:
  environment: environment-rtd.yml

sphinx:
  configuration: docs/source/conf.py